version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - rabbitmq

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - rabbitmq

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      - rabbitmq
